USE biketimer;

INSERT INTO users(id,
    fb_id,
    bt_name,
    email,
    fb_access_token,
    fb_name,
    fb_surname,
    roles,
    friends_ids)
VALUES (00000000-0000-0000-0000-000000000001, '100000204641942', 'Jacek Dalkowski', 'jacekdalkowski@gmail.com',
'CAACEdEose0cBAO4ZAJCMwkT6N6nRCJJVjkHQWP22Xg0kisIYHRUbrT7qhcP5vtpClEONv1JWoSfJFkE0sPoqr1nqSD50oXDGU9B9OjY6YeqqIZAhcbN7ZAge71thrDNgQTZCs4iKr583krRPwJgTCNjV8sG6vF2RlfxBgJlteDZAJMMI0Snpz1UqZCTpSUG8BY5OZBsLk3mqwZDZD', 'Jacek', 'Dalkowski', ['biker'], null); 